"""Generate self-contained sensor installer scripts.

Each installer bakes in the manager URL and the enrollment token, performs
the enrollment call, persists the sensor token, and installs a small
heartbeat agent (systemd unit on Linux, Scheduled Task on Windows).
"""

from __future__ import annotations

from dataclasses import dataclass

SUPPORTED_PLATFORMS = ("linux", "windows")


class InstallerConfigError(ValueError):
    """Raised when we cannot generate an installer (missing token, etc.)."""


@dataclass(frozen=True)
class InstallerSpec:
    platform: str
    filename: str
    content_type: str
    body: str


def _normalize_manager_url(manager_url: str) -> str:
    if not manager_url:
        raise InstallerConfigError("Manager URL is required to generate an installer")
    return manager_url.rstrip("/")


def _require_token(enrollment_token: str) -> str:
    token = (enrollment_token or "").strip()
    if not token:
        raise InstallerConfigError(
            "Sensor enrollment is not configured on this manager. Set "
            "MOONWING_SENSOR_ENROLLMENT_TOKEN and restart the API before "
            "downloading an installer."
        )
    return token


def _bash_quote(value: str) -> str:
    """Quote a value for safe inclusion inside single-quoted bash string."""
    return value.replace("'", "'\"'\"'")


def _ps_quote(value: str) -> str:
    """Quote a value for safe inclusion inside PowerShell single-quoted string."""
    return value.replace("'", "''")


def render_linux_installer(*, manager_url: str, enrollment_token: str) -> str:
    url = _normalize_manager_url(manager_url)
    token = _require_token(enrollment_token)
    return _LINUX_TEMPLATE.format(
        manager_url=_bash_quote(url),
        enrollment_token=_bash_quote(token),
    )


def render_windows_installer(*, manager_url: str, enrollment_token: str) -> str:
    url = _normalize_manager_url(manager_url)
    token = _require_token(enrollment_token)
    return _WINDOWS_TEMPLATE.format(
        manager_url=_ps_quote(url),
        enrollment_token=_ps_quote(token),
    )


def render_installer(*, platform: str, manager_url: str, enrollment_token: str) -> InstallerSpec:
    normalized = (platform or "").strip().lower()
    if normalized in {"linux"}:
        body = render_linux_installer(manager_url=manager_url, enrollment_token=enrollment_token)
        return InstallerSpec(
            platform="linux",
            filename="moonwing-sensor-install.sh",
            content_type="text/x-shellscript",
            body=body,
        )
    if normalized in {"windows", "win", "win32"}:
        body = render_windows_installer(manager_url=manager_url, enrollment_token=enrollment_token)
        return InstallerSpec(
            platform="windows",
            filename="moonwing-sensor-install.ps1",
            content_type="text/x-powershell",
            body=body,
        )
    raise InstallerConfigError(f"Unsupported sensor platform: {platform!r}")


# NOTE: In-repo equivalents (env / CLI manager URL + token): deploy/sensors/
# Braces inside templates that must NOT be substituted by .format() are doubled ({{ / }}).
# Substitution placeholders are {manager_url} and {enrollment_token}.
_LINUX_TEMPLATE = r"""#!/usr/bin/env bash
# Moonwing endpoint sensor installer (Linux)
# Generated by the Moonwing manager. Do not commit this file — it embeds
# the enrollment token for this manager.

set -euo pipefail

MANAGER_URL='{manager_url}'
ENROLLMENT_TOKEN='{enrollment_token}'

INSTALL_DIR="/opt/moonwing-sensor"
CONFIG_DIR="/etc/moonwing"
CONFIG_FILE="$CONFIG_DIR/sensor.env"
AGENT_SCRIPT="$INSTALL_DIR/moonwing-sensor.sh"
SERVICE_FILE="/etc/systemd/system/moonwing-sensor.service"

if [[ $EUID -ne 0 ]]; then
  echo "[moonwing-sensor] must run as root" >&2
  exit 1
fi

for tool in curl python3; do
  if ! command -v "$tool" >/dev/null 2>&1; then
    echo "[moonwing-sensor] missing required tool: $tool" >&2
    exit 1
  fi
done

HOSTNAME_VALUE="$(hostname -f 2>/dev/null || hostname)"
OS_NAME="$(. /etc/os-release 2>/dev/null && echo "${{PRETTY_NAME:-Linux}}" || echo "Linux")"
SENSOR_VERSION="0.1.0"

mkdir -p "$INSTALL_DIR" "$CONFIG_DIR"
chmod 750 "$CONFIG_DIR"

echo "[moonwing-sensor] enrolling with $MANAGER_URL"
ENROLL_PAYLOAD=$(python3 - <<PY
import json
print(json.dumps({{
    "enrollment_token": "$ENROLLMENT_TOKEN",
    "hostname": "$HOSTNAME_VALUE",
    "platform": "linux",
    "os_name": "$OS_NAME",
    "sensor_version": "$SENSOR_VERSION",
    "labels": [],
}}))
PY
)

ENROLL_RESPONSE=$(curl -sS -f -X POST "$MANAGER_URL/api/sensors/enroll" \
  -H "Content-Type: application/json" \
  -d "$ENROLL_PAYLOAD")

SENSOR_ID=$(printf '%s' "$ENROLL_RESPONSE" | python3 -c 'import json,sys;print(json.load(sys.stdin)["sensor_id"])')
SENSOR_TOKEN=$(printf '%s' "$ENROLL_RESPONSE" | python3 -c 'import json,sys;print(json.load(sys.stdin)["token"])')

if [[ -z "$SENSOR_ID" || -z "$SENSOR_TOKEN" ]]; then
  echo "[moonwing-sensor] enrollment failed: $ENROLL_RESPONSE" >&2
  exit 1
fi

cat > "$CONFIG_FILE" <<EOF
MOONWING_MANAGER_URL=$MANAGER_URL
MOONWING_SENSOR_ID=$SENSOR_ID
MOONWING_SENSOR_TOKEN=$SENSOR_TOKEN
MOONWING_SENSOR_VERSION=$SENSOR_VERSION
EOF
chmod 600 "$CONFIG_FILE"

cat > "$AGENT_SCRIPT" <<'AGENT'
#!/usr/bin/env bash
# Minimal Moonwing sensor heartbeat loop.
set -u
# shellcheck source=/etc/moonwing/sensor.env
source /etc/moonwing/sensor.env

heartbeat_interval=${{MOONWING_SENSOR_HEARTBEAT_SECONDS:-60}}

while true; do
  inventory=$(python3 - <<PY
import json, platform, socket
print(json.dumps({{
    "hostname": socket.gethostname(),
    "fqdn": socket.getfqdn(),
    "kernel": platform.release(),
    "machine": platform.machine(),
    "python": platform.python_version(),
}}))
PY
)
  payload=$(python3 - <<PY
import json, os
print(json.dumps({{
    "inventory": json.loads(os.environ["INVENTORY"]),
    "network": {{}},
    "sensor_version": os.environ.get("MOONWING_SENSOR_VERSION", ""),
}}))
PY
)
  INVENTORY="$inventory" \
    curl -sS -f -X POST "$MOONWING_MANAGER_URL/api/sensors/$MOONWING_SENSOR_ID/heartbeat" \
    -H "Authorization: Bearer $MOONWING_SENSOR_TOKEN" \
    -H "Content-Type: application/json" \
    -d "$payload" >/dev/null || echo "[moonwing-sensor] heartbeat failed at $(date -Iseconds)" >&2
  sleep "$heartbeat_interval"
done
AGENT
chmod 750 "$AGENT_SCRIPT"

cat > "$SERVICE_FILE" <<EOF
[Unit]
Description=Moonwing Endpoint Sensor
After=network-online.target
Wants=network-online.target

[Service]
Type=simple
EnvironmentFile=$CONFIG_FILE
ExecStart=$AGENT_SCRIPT
Restart=always
RestartSec=10
User=root

[Install]
WantedBy=multi-user.target
EOF

systemctl daemon-reload
systemctl enable --now moonwing-sensor.service

echo "[moonwing-sensor] installed and running. sensor_id=$SENSOR_ID"
echo "[moonwing-sensor] view status: systemctl status moonwing-sensor"
echo "[moonwing-sensor] logs:        journalctl -u moonwing-sensor -f"
"""


_WINDOWS_TEMPLATE = r"""#requires -RunAsAdministrator
# Moonwing endpoint sensor installer (Windows)
# Generated by the Moonwing manager. Do not commit this file - it embeds
# the enrollment token for this manager.

$ErrorActionPreference = 'Stop'

$ManagerUrl       = '{manager_url}'
$EnrollmentToken  = '{enrollment_token}'
$SensorVersion    = '0.1.0'

$InstallDir = 'C:\ProgramData\Moonwing\sensor'
$ConfigFile = Join-Path $InstallDir 'sensor.env'
$AgentScript = Join-Path $InstallDir 'moonwing-sensor.ps1'

if (-not (Test-Path $InstallDir)) {{
    New-Item -ItemType Directory -Path $InstallDir -Force | Out-Null
}}

$Hostname = [System.Net.Dns]::GetHostName()
try {{
    $OsName = (Get-CimInstance Win32_OperatingSystem).Caption
}} catch {{
    $OsName = 'Windows'
}}

Write-Host "[moonwing-sensor] enrolling with $ManagerUrl"

$EnrollPayload = @{{
    enrollment_token = $EnrollmentToken
    hostname         = $Hostname
    platform         = 'windows'
    os_name          = $OsName
    sensor_version   = $SensorVersion
    labels           = @()
}} | ConvertTo-Json -Compress

$EnrollResponse = Invoke-RestMethod `
    -Method Post `
    -Uri "$ManagerUrl/api/sensors/enroll" `
    -ContentType 'application/json' `
    -Body $EnrollPayload

$SensorId    = $EnrollResponse.sensor_id
$SensorToken = $EnrollResponse.token

if (-not $SensorId -or -not $SensorToken) {{
    throw "Enrollment failed: $($EnrollResponse | ConvertTo-Json -Depth 4)"
}}

@(
    "MOONWING_MANAGER_URL=$ManagerUrl",
    "MOONWING_SENSOR_ID=$SensorId",
    "MOONWING_SENSOR_TOKEN=$SensorToken",
    "MOONWING_SENSOR_VERSION=$SensorVersion"
) | Set-Content -Path $ConfigFile -Encoding ASCII

$AgentBody = @'
$ErrorActionPreference = 'Continue'
$ConfigFile = 'C:\ProgramData\Moonwing\sensor\sensor.env'

$cfg = @{{}}
foreach ($line in (Get-Content $ConfigFile)) {{
    if ($line -match '^(MOONWING_[A-Z_]+)=(.*)$') {{
        $cfg[$Matches[1]] = $Matches[2]
    }}
}}

$ManagerUrl   = $cfg['MOONWING_MANAGER_URL']
$SensorId     = $cfg['MOONWING_SENSOR_ID']
$SensorToken  = $cfg['MOONWING_SENSOR_TOKEN']
$SensorVersion = $cfg['MOONWING_SENSOR_VERSION']

$Inventory = @{{
    hostname = [System.Net.Dns]::GetHostName()
    os_name  = (Get-CimInstance Win32_OperatingSystem).Caption
    kernel   = [System.Environment]::OSVersion.Version.ToString()
    machine  = [System.Environment]::OSVersion.Platform.ToString()
}}

$Payload = @{{
    inventory      = $Inventory
    network        = @{{}}
    sensor_version = $SensorVersion
}} | ConvertTo-Json -Compress

try {{
    Invoke-RestMethod `
        -Method Post `
        -Uri "$ManagerUrl/api/sensors/$SensorId/heartbeat" `
        -Headers @{{ Authorization = "Bearer $SensorToken" }} `
        -ContentType 'application/json' `
        -Body $Payload | Out-Null
}} catch {{
    Write-EventLog -LogName Application -Source 'Moonwing Sensor' `
        -EntryType Warning -EventId 1001 `
        -Message "Heartbeat failed: $($_.Exception.Message)" -ErrorAction SilentlyContinue
}}
'@

Set-Content -Path $AgentScript -Value $AgentBody -Encoding UTF8

if (-not [System.Diagnostics.EventLog]::SourceExists('Moonwing Sensor')) {{
    [System.Diagnostics.EventLog]::CreateEventSource('Moonwing Sensor', 'Application')
}}

$TaskName = 'Moonwing Sensor Heartbeat'
$Action = New-ScheduledTaskAction -Execute 'powershell.exe' `
    -Argument "-NoProfile -ExecutionPolicy Bypass -File `"$AgentScript`""
$Trigger = New-ScheduledTaskTrigger -Once -At (Get-Date).AddMinutes(1) `
    -RepetitionInterval (New-TimeSpan -Minutes 1) `
    -RepetitionDuration ([System.TimeSpan]::MaxValue)
$Settings = New-ScheduledTaskSettingsSet -AllowStartIfOnBatteries -DontStopIfGoingOnBatteries -StartWhenAvailable

if (Get-ScheduledTask -TaskName $TaskName -ErrorAction SilentlyContinue) {{
    Unregister-ScheduledTask -TaskName $TaskName -Confirm:$false
}}

Register-ScheduledTask -TaskName $TaskName -Action $Action `
    -Trigger $Trigger -Settings $Settings -RunLevel Highest `
    -User 'SYSTEM' | Out-Null

Write-Host "[moonwing-sensor] installed. sensor_id=$SensorId"
Write-Host "[moonwing-sensor] heartbeat task: $TaskName"
"""
