---
all:
  children:
    moonwing_manager:
      hosts:
        secops:
          ansible_host: 192.168.1.215
          ansible_user: dduggan
          ansible_python_interpreter: /usr/bin/python3
    moonwing_sensors:
      hosts: {}
      # Add sensor endpoints here, e.g.:
      # danspc:
      #   ansible_host: 192.168.1.50
      #   ansible_user: Administrator
